name: quiz_application
description: "QuizApplication is a fun, interactive, and intelligently crafted quiz app designed to challenge your knowledge across various topics."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  html_unescape: ^2.0.0
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sound/correct-answer.mp3
    - assets/sound/wrong-answer.wav

